name: Publish to NPM
on:
  release:
    types: [published]
  # Enables running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate with Google Cloud
        id: "auth"
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          token_format: "access_token"
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          cd javascript/
          npm install
          npm run build
          npm run test
        env:
          EE_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}

  publish-npm:
    if: "!github.event.release.prerelease"  # Only run if not a prerelease.
    needs: smoke-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          cd javascript/
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
